name: MacRDP
on: 
  workflow_dispatch:

jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:
    - name: Setting Up Remote Access
      run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/JZ02/MacRDP/main/start.sh"
          chmod +x start.sh
          bash start.sh

    - name: Retrieve VNC Login Details
      run: |
          curl -s -o login.sh -L "https://raw.githubusercontent.com/JZ02/MacRDP/main/login.sh"
          chmod +x login.sh
          bash login.sh

    - name: Keep MacOS Instance Running
      uses: mxschmitt/action-tmate@v2
